name: Create release package

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV &&
          echo "PKG_NAME=`basename $GITHUB_REPOSITORY -private`" >> $GITHUB_ENV

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6

      - name: Install Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903  # v6
        with:
          node-version: 22
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install npm dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}

      - name: Install PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2
        with:
          php-version: 8.3

      - name: Composer install (for indexing of vendor blade classes)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-dev

      - name: Run build task
        run: npm run build

      - name: Clean build
        run: rm -r node_modules .git

      - name: Clear config cache
        run: php artisan config:clear

      - name: Clear route cache
        run: php artisan route:clear

      - run: 'echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > public/version.json'
        shell: bash

      - name: Create tar
        run: tar -czf ${{ env.PKG_NAME }}_${{ env.RELEASE_VERSION }}.tar.gz ./app ./bootstrap ./config ./lang ./public ./resources ./routes ./vendor ./composer.json

      - name: Upload release tar
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4  # v5
        with:
          name: ${{ env.PKG_NAME }}_${{ env.RELEASE_VERSION }}
          path: ${{ env.PKG_NAME }}_${{ env.RELEASE_VERSION }}.tar.gz
